import { StyleSheet } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { defaultColors } from '../../../themes';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: defaultColors.screenBackground },
  btn: { marginTop: 32, width: wp(100) - 32, marginHorizontal: 16 },
  containerCenter: {
    height: hp(100),
    width: wp(100) - 32,
    position: 'absolute',
    top: hp(26.5),
    marginHorizontal: 16,
  },
  containerForm: {
    backgroundColor: 'white',
    width: wp(100) - 32,
    borderRadius: 10,
    elevation: 10,
    zIndex: 2,
    marginTop: 32,
  },
  formUsername: {
    paddingLeft: 32 + 16,
    paddingRight: 16,
    borderColor: defaultColors.primary,
    color: '#222222',
    fontFamily: 'Poppins-Regular',
    marginHorizontal: 16,
    width: wp(100) - 64,
    height: 50,
    marginTop: 16,
    borderRadius: 10,
    backgroundColor: '#F4F4F4',
    fontSize: 15,
  },
  containerIconUsername: {
    position: 'absolute',
    left: 16 + 12,
    top: 16 + 12,
    flexDirection: 'row',
  },
  iconUsername: {
    resizeMode: 'contain',
    width: 26,
    height: 26,
  },
  placeholder: { marginLeft: 10, top: 2 },
  formPassword: {
    borderColor: defaultColors.primary,
    fontFamily: 'Poppins-Regular',
    paddingLeft: 32 + 16,
    paddingRight: 16,
    fontSize: 15,
    color: '#222222',
    marginHorizontal: 16,
    width: wp(100) - 64,
    height: 50,
    marginBottom: 16,
    marginTop: 8,
    borderRadius: 10,
    backgroundColor: '#F4F4F4',
  },
  containerIconPassword: {
    position: 'absolute',
    left: 12,
    top: 16 + 4,
    flexDirection: 'row',
    width: wp(100) - 64,
  },
  iconPassword: {
    resizeMode: 'contain',
    width: 26,
    height: 26,
    marginLeft: 16,
    position: 'absolute',
    top: 20,
    left: 13,
  },
  containerEye: {
    top: 7,
    height: 50,
    width: 65,
    position: 'absolute',
    right: 13,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerForgotLogin: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  containerForgot: {
    width: wp(50),
    height: 50,
    marginTop: 16,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonLogin: {
    backgroundColor: defaultColors.white,
    width: wp(50) - 32 - 14,
    height: 50,
    marginTop: 16,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  back: {
    zIndex: 2,
    height: 28,
    width: 28,
    backgroundColor: 'white',
    borderRadius: 28 / 2,
    position: 'absolute',
    top: hp(5),
    left: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circle3: {
    position: 'absolute',
    top: hp(65),
    right: hp(5),
    zIndex: -1,
  },
  imgHeader: { width: wp(100), height: wp(70.91), resizeMode: 'cover' },
  underline: {
    height: 1.5,
    backgroundColor: defaultColors.primary,
  },
  containerImgHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  appName: { marginTop: 5, marginBottom: 8 },
  containerText: { flexDirection: 'row', zIndex: 2 },
  circle4: {
    position: 'absolute',
    top: hp(30),
    right: hp(5),
    zIndex: 1,
  },
  circle: {
    position: 'absolute',
    top: hp(82),
    left: hp(10),
    zIndex: 1,
  },
  circle2: {
    position: 'absolute',
    top: hp(80),
    right: hp(10),
    zIndex: 1,
  },
});
